apiVersion: v1
kind: Pod
metadata:
  name: hvac-log680
spec:
  containers:
    - name: hvac-controller
      image: baotranc/log680-tp2-gr1-eq4:latest 
      envFrom:
        - configMapRef:
            name: hvac-config
        - secretRef:
            name: fake-hvac-token
      resources:
        requests:
          memory: "15Mi"
          cpu: "20m"
        limits:
          memory: "30Mi"
          cpu: "40m"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred

